name: North True
favicon: null
layout_spectrum: 0.23732059611938894
typography_spectrum: 0.5960066632833332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5894041967112571
  lightness: 0.23747446900233626
  saturation: 0.36053589219227433
  rhythmicContrast: 0.866231853608042
purpose: []
